# The Trusty beta Build Environment
sudo: required
dist: trusty
os: linux
compiler: g++
language: cpp
  
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt591-trusty
  - sudo apt-get update
 
install:
  - sudo apt-get install qt59base qt59widgets qt59serialport
  - source /opt/qt59/bin/qt59-env.sh
  
script:
  - /opt/qt59/bin/qmake PREFIX=/usr
  - make
