# The Trusty beta Build Environment
sudo: required
dist: trusty
os: linux
compiler: gcc
language: c++
  
before_install:
 - sudo apt-add-repository --yes ppa:beineri/opt-qt551-trusty
 - sudo apt-get -qq update

before_script:
  - QTDIR="/opt/qt55"
  - PATH="$QTDIR/bin:$PATH"
  - source /opt/qt55/bin/qt55-env.sh
 
install:
  - sudo apt-get --yes install qt55base qt55imageformats qt55svg libqt5serialport5

script:
 - qmake
 - make
