# The Trusty beta Build Environment
sudo: required
dist: trusty
os: linux
compiler: g++
language: cpp
  
before_install:
 - sudo apt-get update
 
install:
  - sudo apt-get --yes install qtbase5-dev libqt5serialport5-dev libqt5serialport5

script:
 - qmake EngineMonitor.pro
 - make
