# The Trusty beta Build Environment
sudo: required
dist: trusty
language: c++

install:
  - sudo apt-get install -y qt5-default qttools5-dev-tools #install necessary Qt files

script:
  - qmake "CONFIG+=debug" EngineMonitor.pro #we gonna compile for Unit test first
  - make
  - ./EngineMonitor #run unit test